#!/usr/bin/bash
WORDLIST=$(dirname "$0")/diceware.wordlist.asc

digits() {
    declare -i d
    od -tu4 -w4 -v /dev/random | while read -r address d; do
	if [[ $d -lt 1934917632 ]]; then
	    printf '%s\n%s\n' \
		   $(( x = d % 7776, d /= 7776, x )) \
		   $(( x = d % 7776, d /= 7776, x ))
	fi
    done
}

digits | for phrase in ${*:-6}; do
    sep=
    while ((phrase-- > 0)); do
	read -r
	printf '%s%s' "$sep" "$(sed -En "$((REPLY + 3))s/^[0-9]+\t(.*)$/\1/p" "$WORDLIST")"
	sep=' '
    done
    echo
done
