#!/usr/bin/bash

digits() {
    declare -i d
    od -tu4 -w4 -v /dev/random | while read -r address d; do
	if [[ $d -lt 2176782336 ]]; then
	    printf '%s%s%s%s%s%s%s%s%s%s%s%s' \
		   $(( x = d % 6 + 1, d /= 6, x )) \
		   $(( x = d % 6 + 1, d /= 6, x )) \
		   $(( x = d % 6 + 1, d /= 6, x )) \
		   $(( x = d % 6 + 1, d /= 6, x )) \
		   $(( x = d % 6 + 1, d /= 6, x )) \
		   $(( x = d % 6 + 1, d /= 6, x )) \
		   $(( x = d % 6 + 1, d /= 6, x )) \
		   $(( x = d % 6 + 1, d /= 6, x )) \
		   $(( x = d % 6 + 1, d /= 6, x )) \
		   $(( x = d % 6 + 1, d /= 6, x )) \
		   $(( x = d % 6 + 1, d /= 6, x )) \
		   $(( x = d % 6 + 1, d /= 6, x ))
	fi
    done
}

sep=
digits | for i in ${*:-5}; do
    read -rn"$i" && printf '%s%s' "$sep" "$REPLY"
    sep=' '
done
echo
